env:
  global:
    - CC_TEST_REPORTER_ID=8396b692ab81c7e4778a24aa0c8c6c1a2db4cd42a0b4e9ec08aadf64cd977092
language: node_js
node_js:
  - 'stable'
  - 'lts/*'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm run lint && npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
